version: '3.8'

services:
  # Banco de dados MariaDB
  database:
    build:
      context: ./Infra
      dockerfile: Dockerfile
    container_name: mariadb_users
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: usersdb
      MYSQL_USER: apiuser
      MYSQL_PASSWORD: apipassword
    ports:
      - "3306:3306"
    volumes:
      - mariadb_data:/var/lib/mysql
    networks:
      - app_network
    healthcheck:
      test: ["CMD", "mariadb-admin", "ping", "-h", "localhost", "-u", "root", "-prootpassword"]
      timeout: 10s
      retries: 5
      interval: 30s
      start_period: 30s


volumes:
  mariadb_data:

networks:
  app_network:
    driver: bridge